List<String> line1 = [
  "Helwan",
  "Ain Helwan",
  "Helwan University",
  "Wadi Hof",
  "Hadayek Helwan",
  "El-Maasara",
  "Tora El-Asmant",
  "Kozzika",
  "Tora El-Balad",
  "Sakanat El-Maadi",
  "Maadi",
  "Hadayek El-Maadi",
  "Dar El-Salam",
  "El-Zahraa",
  "Mar Girgis",
  "El-Malek El-Saleh",
  "Al-Sayeda Zeinab",
  "Saad Zaghloul",
  "Sadat",
  "Nasser",
  "Orabi",
  "Al-Shohadaa",
  "Ghamra",
  "El-Demerdash",
  "Manshiet El-Sadr",
  "Kobri El-Qobba",
  "Hammamat El-Qobba",
  "Saray El-Qobba",
  "Hadayeq El-Zaitoun",
  "Helmeyet El-Zaitoun",
  "El-Matareyya",
  "Ain Shams",
  "Ezbet El-Nakhl",
  "El-Marg",
  "New El-Marg",
];

List<String> line2 = [
  "Shoubra El-Kheima",
  "Kolleyyet El-Zeraa",
  "Mezallat",
  "Khalafawy",
  "St. Teresa",
  "Rod El-Farag",
  "Masarra",
  "Al-Shohadaa",
  "Attaba",
  "Mohamed Naguib",
  "Sadat",
  "Opera",
  "Dokki",
  "Bohooth",
  "Cairo University",
  "Faisal",
  "Giza",
  "Omm El-Misryeen",
  "Sakiat Mekki",
  "El-Mounib",
];

List<String> line3 = [
  "Adly Mansour",
  "El-Haykstep",
  "Omar Ibn El-Khattab",
  "Qobaa",
  "Hesham Barakat",
  "El-Nozha",
  "El-Shams Club",
  "Alf Maskan",
  "Heliopolis",
  "Haroun",
  "Al-Ahram",
  "Koleyet El-Banat",
  "Stadium",
  "Fair Zone",
  "Abbassia",
  "Abdou Pasha",
  "El-Geish",
  "Bab El-Shaaria",
  "Attaba",
  "Nasser",
  "Maspero",
  "Safaa Hegazy",
  "Kit Kat",
  "Sudan",
  "Imbaba",
  "El-Bohy",
  "Al-Qawmia",
  "Ring Road",
  "Rod El-Farag",
];

List<String> line3CairoUniversityBranch = [
  "Kit Kat",
  "Al-Tawfikia",
  "Wadi El-Nile",
  "Gameat El-Dowal",
  "Bulak El-Dakrour",
  "Cairo University",
];

List<String> allStations =
    <String>{
      ...line1,
      ...line2,
      ...line3,
      ...line3CairoUniversityBranch,
    }.toList()..sort();